services:
  postgres:
    image: postgres:16.2-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kia_logix
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:6.2-alpine
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge

volumes:
  pg-data:
  redis-data:
    driver: local
