services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgis
      - redis
      - faktory
    networks:
      - backend-network

  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kia_logix
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:6.2-alpine
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network

  faktory:
    image: contribsys/faktory:1.5.1
    container_name: faktory
    ports:
      - "7419:7419"  # default port
      - "7420:7420"  # web UI port
    environment:
      FAKTORY_CONCURRENCY: 10
    volumes:
      - faktory_data:/var/lib/faktory
    networks:
      - backend-network



networks:
  backend-network:
    driver: bridge

volumes:
  faktory_data:
    driver: local
  pg-data:
  redis-data:
    driver: local
